export const clientLogos = [
  { name: "Google", src: "/images/clients/google-logo-keskese.png" },
  { name: "Samsung", src: "/images/clients/keskese-client-samsung.png" },
  { name: "MTN", src: "/images/clients/mtn-logo-keskese.png" },
  { name: "Cadbury", src: "/images/clients/keskese-client-cadbury.png" },
  { name: "Unilever", src: "/images/clients/uniliver-logo-keskese.png" },
  { name: "AB InBev", src: "/images/clients/abinbev-logo-keskese.png" },
  { name: "Bacardi", src: "/images/clients/bacardi-logo-keskese.png" },
  { name: "Ecobank", src: "/images/clients/keskese-logo-ecobank.png" },
  { name: "Huawei", src: "/images/clients/keskese-client-hauwei.png" },
  { name: "OLX", src: "/images/clients/keskese-client-olx.png" },
  { name: "Lafarge", src: "/images/clients/keskese-client-lafarge.png" },
  { name: "Suzuki", src: "/images/clients/keskese-client-suzuki.png" },
  { name: "Nigerian Breweries", src: "/images/clients/keskese-client-NB.png" },
  { name: "BAT", src: "/images/clients/keskese-client-bat.png" },
  { name: "CHI Limited", src: "/images/clients/chi-logo-keskese.png" },
  { name: "CWAY", src: "/images/clients/keskese-client-cway.png" },
  { name: "Lumos", src: "/images/clients/keskese-client-lumos.png" },
  { name: "Sun King", src: "/images/clients/keskese-client-sun-king.png" },
  { name: "MoMo", src: "/images/clients/keskese-client-momo.png" },
  { name: "UAC Foods", src: "/images/clients/uacfood-logo-keskese.png" },
  { name: "La Casera", src: "/images/clients/keskese-client-lacasera.png" },
  { name: "Breezer", src: "/images/clients/keskese-client-breezer.png" },
  { name: "33 Export", src: "/images/clients/keskese-client-33-xport.png" },
  { name: "NSA", src: "/images/clients/keskese-client-NSA.png" },
  { name: "Global Golf", src: "/images/clients/keskese-client-globalgolf.png" },
] as const;
